# Generated by Django 5.2.1 on 2025-05-16 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default="Midlertidig adresse"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="agree_to_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="birth_date",
            field=models.DateField(default=datetime.date(2025, 5, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="Testby", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="color_1",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="order",
            name="color_2",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="order",
            name="color_3",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="order",
            name="color_4",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="order",
            name="color_5",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="order",
            name="concept_description",
            field=models.TextField(default="Midlertidig konseptbeskrivelse"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default="test@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(default="Testbruker", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="group_name",
            field=models.CharField(default="Midlertidig russenavn", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="00000000", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(default="0000", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
