# Generated by Django 5.2.1 on 2025-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_address_order_agree_to_terms_order_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
