# Generated by Django 5.2.1 on 2025-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_review_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeaserVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("basic", "Basic teaser"),
                            ("premium", "Premium teaser"),
                            ("custom", "Skreddersydd teaser"),
                        ],
                        max_length=50,
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                ("concept_description", models.TextField()),
                ("video_style", models.CharField(max_length=100)),
                ("music_preference", models.CharField(blank=True, max_length=100)),
                (
                    "uploaded_files",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("agree_to_terms", models.BooleanField(default=False)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="order",
            old_name="uploaded_file",
            new_name="uploaded_files",
        ),
    ]
