# Generated by Django 4.2.21 on 2025-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="is_answered",
            field=models.BooleanField(default=False),
        ),
    ]
