# Generated by Django 4.2.21 on 2025-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_contactmessage_is_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="admin_note",
            field=models.TextField(blank=True),
        ),
    ]
