# Generated by Django 4.2.21 on 2025-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_order_admin_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
