# Generated by Django 4.2.21 on 2025-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_order_is_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="teaservideo",
            name="admin_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="teaservideo",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
